### ISSUE TITLE
Understanding about one sentence in the paper.

### ISSUE THREAD

**Issue by Lzshanshan** [hoshino042/bilateral_normal_integration#7]
Hello,

Thanks for this amazing work, but I am confused about one sentence in the paper. In the Section 2.1, you mention "we omit the dependencies of **p** and **n** on **u** for brevity."

Could you please give me more explanations on "dependencies"? I mean what do dependencies of **p** and **n** on **u** mean here? And, when ommitting dependencies, what are the assumptions?

Thank you for your time and patience.

Zhenshan,
Regards

**Comment by xucao-42** [comment]
Hi, **p** and **n** can be both considered as functions defined on the image plane, thus **p(u)** and **n(u)**. By "omitting the dependencies", I mean we write the equations in terms of **p** and **n** instead of **p(u)** and **n(u)**. But still, we mean the equations should hold at each pixel **u** in the image plane. No assumptions are introduced here.
 
BTW, **p(u)** is just the point map, where each pixel **u** records the XYZ coordinates of a 3D point.

**Comment by Lzshanshan** [comment]
Thanks for your quick reply and clear explanation!
